// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0uSeOjSKDTaVMjkvxKifdu-b9mHzNdyI',
    appId: '1:903785143344:web:0ec81391c4a5c41e6be1f5',
    messagingSenderId: '903785143344',
    projectId: 'jf-app-a7edc',
    authDomain: 'jf-app-a7edc.firebaseapp.com',
    storageBucket: 'jf-app-a7edc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zyg-PtdKJ9VNk08tn3IrHxTqqtiWazs',
    appId: '1:903785143344:android:fffe9a2f4853494d6be1f5',
    messagingSenderId: '903785143344',
    projectId: 'jf-app-a7edc',
    storageBucket: 'jf-app-a7edc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ZqxZAbyjLwZScb_SCkKSy8URcWRc2Yc',
    appId: '1:903785143344:ios:8176ed52ba36846b6be1f5',
    messagingSenderId: '903785143344',
    projectId: 'jf-app-a7edc',
    storageBucket: 'jf-app-a7edc.firebasestorage.app',
    iosBundleId: 'com.example.jfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ZqxZAbyjLwZScb_SCkKSy8URcWRc2Yc',
    appId: '1:903785143344:ios:8176ed52ba36846b6be1f5',
    messagingSenderId: '903785143344',
    projectId: 'jf-app-a7edc',
    storageBucket: 'jf-app-a7edc.firebasestorage.app',
    iosBundleId: 'com.example.jfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0uSeOjSKDTaVMjkvxKifdu-b9mHzNdyI',
    appId: '1:903785143344:web:626a245a896926596be1f5',
    messagingSenderId: '903785143344',
    projectId: 'jf-app-a7edc',
    authDomain: 'jf-app-a7edc.firebaseapp.com',
    storageBucket: 'jf-app-a7edc.firebasestorage.app',
  );
}
